name: test and build gem
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: test + build
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Set up ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: rspec
      run: |
        gem install rspec
        rspec

    - name: build gem
      run: |
        gem build cfn-guardian.gemspec