name: release gem

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and publish gem
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    
    - name: Set up ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Publish gem to RubyGems and Github packages
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${GITHUB_TOKEN}\n:rubygems_api_key: #{RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        gem build cfn-guardian.gemspec
        gem push cfn-guardian-*.gem
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} cfn-guardian-*.gem
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        OWNER: ${{ github.repository_owner }}
