name: release gem

on:
  release:
    types: [published]

jobs:
  build:
    name: Build + Publish Gem
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Publish Gem to Github Packages Respository
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n:rubygems_api_key: #{RUBYGEMS_API_KEY}" > $HOME/.gem/credentials
        gem build cfn-guardian.gemspec
        gem push cfn-guardian-*.gem
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} cfn-guardian-*.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        OWNER: ${{ github.repository_owner }}
